version: '3.1'
services:
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered:/data/nodered
    networks:
      - nodered
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - nodered
  mongo-admin:
    image: mongo-express:0.54
    ports:
      - "8882:8081"
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - nodered
    depends_on:
      - mongo
networks:
  nodered: 